theme = "cactus"
baseURL = '/'
languageCode = 'en-gb'
title = 'Max Novakovic'

[params]
  colortheme = "classic" # dark, light, white, or classic
  description = "Experienced full-stack engineer currently available for freelance work. I can work on all the technical aspects needed in order to get your new product, app or business idea off the ground. Get in touch!"
  # I can build your entire project quickly and reliably, get in touch!
  mainSection = "project"
  logo = "images/diamond.png"
  css = ["css/custom.css"]

[[params.social]]
  name = "email"
  link = "max@maxnov.com"

[[params.social]]
  name = "github"
  link = "https://github.com/betamax"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/max-novakovic/"